main:
  - name: เรียนรู้
    URL: learn
    weight: 1
    identifier: learn
  - name: หนังสือ
    parent: learn
    URL: learn/books
    weight: 2
  - name: เส้นทางการเรียนรู้
    parent: learn
    URL: learn/learning-path
    weight: 3
  - name: แพทเทิร์น
    parent: learn
    URL: learn/patterns
    weight: 4
  - name: งานวิจัย
    parent: learn
    URL: learn/research
    weight: 5
  - name: กิจกรรม
    URL: events
    weight: 2
  - name: ชุมชน
    identifier: community
    URL: community
    weight: 3
  - name: เรื่องราว
    URL: stories
    weight: 4
  - name: รายชื่อผู้ให้บริการ
    URL: community/services
    parent: community
    weight: 2
  - name: เกี่ยวกับ
    identifier: about
    URL: about
    weight: 5
  - name: ประกาศ
    URL: about/announcements
    parent: about
    weight: 1
  - name: คณะกรรมการและธรรมาภิบาล
    URL: about/board
    parent: about
    weight: 2
  - name: สมาชิก
    URL: about/members
    parent: about
    weight: 3
  - name: ผู้สนับสนุน
    URL: about/sponsors
    parent: about
    weight: 4
  - name: จรรยาบรรณ
    URL: about/codeofconduct
    parent: about
    weight: 5
  - name: ติดต่อเรา
    URL: about/contact
    parent: about
    weight: 6
footer_left:
  - name: เรียนรู้
    URL: learn
    weight: 1
    post: bold
  - name: หนังสือ
    URL: learn/books
    weight: 2
  - name: เส้นทางการเรียนรู้
    URL: learn/learning-path
    weight: 3
  - name: แพทเทิร์น
    URL: learn/patterns
    weight: 4
  - name: งานวิจัย
    URL: learn/research
    weight: 5
footer_middle:
  - name: กิจกรรม
    URL: events
    weight: 1
    post: bold
  - name: ชุมชน
    URL: community
    weight: 2
    post: bold
    pre: _blank
  - name: เรื่องราว
    URL: stories
    weight: 3
    post: bold
  - name: รายชื่อผู้ให้บริการ
    URL: community/services
    weight: 4
  - name: ประกาศ
    URL: about/announcements
    weight: 5
footer_right:
  - name: เกี่ยวกับ
    URL: about
    weight: 1
    post: bold
  - name: คณะกรรมการและธรรมาภิบาล
    URL: about/board
    weight: 2
  - name: สมาชิก
    URL: about/members
    weight: 3
  - name: ผู้สนับสนุน
    URL: about/sponsors
    weight: 4
  - name: จรรยาบรรณ
    URL: about/codeofconduct
    weight: 5
  - name: ติดต่อเรา
    URL: about/contact
    weight: 6
  - name: นโยบายความเป็นส่วนตัว
    URL: about/privacy
    weight: 7